board: developer-kit
skills:
    - name: confluence-reviewer
      source: github.com/siyuqian/devpilot
      version: v0.12.0
      installedAt: 2026-04-06T06:14:04.862255Z
    - name: content-creator
      source: github.com/siyuqian/devpilot
      version: v0.12.0
      installedAt: 2026-04-06T06:14:06.416307Z
    - name: google-go-style
      source: github.com/siyuqian/devpilot
      version: v0.12.0
      installedAt: 2026-04-06T06:14:10.03971Z
    - name: pm
      source: github.com/siyuqian/devpilot
      version: v0.12.0
      installedAt: 2026-04-06T06:14:12.040444Z
    - name: task-executor
      source: github.com/siyuqian/devpilot
      version: v0.12.0
      installedAt: 2026-04-06T06:14:12.969123Z
    - name: task-refiner
      source: github.com/siyuqian/devpilot
      version: v0.12.0
      installedAt: 2026-04-06T06:14:14.652469Z
    - name: trello
      source: github.com/siyuqian/devpilot
      version: v0.12.0
      installedAt: 2026-04-06T06:14:15.534549Z
