//go:build parity

package cache

import (
	"database/sql"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"sort"
	"strings"
	"testing"
	"time"

	_ "modernc.org/sqlite"
)

// TestNativeBackendParityReport builds the devpilot repo with both Go parser
// backends (tree-sitter and native), diffs the resulting nodes/edges, and
// writes an advisory markdown report. The test always passes — it exists to
// produce data for the human rollout decision in N1.16.
//
// Run with:
//
//	go test -tags=parity -count=1 ./internal/graph/cache/ \
//	    -run TestNativeBackendParityReport -v
func TestNativeBackendParityReport(t *testing.T) {
	repoRoot := findRepoRoot(t)
	t.Logf("repo root: %s", repoRoot)

	// --- Tree-sitter run ---
	t.Setenv("DEVPILOT_GRAPH_GO_BACKEND", "")
	home1 := t.TempDir()
	b1, err := NewBuilder(home1, repoRoot)
	if err != nil {
		t.Logf("treesitter NewBuilder: %v", err)
		return
	}
	res1, err := b1.FullBuild()
	if err != nil {
		t.Logf("treesitter FullBuild: %v", err)
		return
	}
	tsNodes, tsEdges := dumpGraph(t, GraphDB(home1, b1.key))
	t.Logf("treesitter: files=%d nodes=%d edges=%d (db nodes=%d edges=%d)",
		res1.FilesParsed, res1.NodesInsert, res1.EdgesInsert, len(tsNodes), len(tsEdges))

	// --- Native run ---
	t.Setenv("DEVPILOT_GRAPH_GO_BACKEND", "native")
	home2 := t.TempDir()
	b2, err := NewBuilder(home2, repoRoot)
	if err != nil {
		t.Logf("native NewBuilder: %v", err)
		return
	}
	res2, err := b2.FullBuild()
	if err != nil {
		t.Logf("native FullBuild: %v", err)
		return
	}
	nvNodes, nvEdges := dumpGraph(t, GraphDB(home2, b2.key))
	t.Logf("native: files=%d nodes=%d edges=%d (db nodes=%d edges=%d)",
		res2.FilesParsed, res2.NodesInsert, res2.EdgesInsert, len(nvNodes), len(nvEdges))

	// --- Build keyed sets ---
	type srcKind struct{ Src, Kind string }
	type triple = parityTriple

	tsSrcKind := map[srcKind]bool{}
	tsTriple := map[triple]bool{}
	for _, e := range tsEdges {
		tsSrcKind[srcKind{e.Src, e.Kind}] = true
		tsTriple[triple{e.Src, e.Dst, e.Kind}] = true
	}
	nvSrcKind := map[srcKind]bool{}
	nvTriple := map[triple]bool{}
	for _, e := range nvEdges {
		nvSrcKind[srcKind{e.Src, e.Kind}] = true
		nvTriple[triple{e.Src, e.Dst, e.Kind}] = true
	}
	nvNodeIDs := map[string]bool{}
	for _, n := range nvNodes {
		nvNodeIDs[n.ID] = true
	}

	// --- Coverage ---
	var coverageMisses []srcKind
	for k := range tsSrcKind {
		if !nvSrcKind[k] {
			coverageMisses = append(coverageMisses, k)
		}
	}
	sort.Slice(coverageMisses, func(i, j int) bool {
		if coverageMisses[i].Src != coverageMisses[j].Src {
			return coverageMisses[i].Src < coverageMisses[j].Src
		}
		return coverageMisses[i].Kind < coverageMisses[j].Kind
	})
	coverageHits := len(tsSrcKind) - len(coverageMisses)

	// --- Net new (native edges not in tree-sitter) ---
	var netNew []triple
	for k := range nvTriple {
		if !tsTriple[k] {
			netNew = append(netNew, k)
		}
	}
	sort.Slice(netNew, func(i, j int) bool {
		if netNew[i].Src != netNew[j].Src {
			return netNew[i].Src < netNew[j].Src
		}
		if netNew[i].Kind != netNew[j].Kind {
			return netNew[i].Kind < netNew[j].Kind
		}
		return netNew[i].Dst < netNew[j].Dst
	})

	// --- Net removed (ts edges not in native), grouped ---
	var dropExternal, dropMisrewrite, dropGenuine []triple
	for k := range tsTriple {
		if nvTriple[k] {
			continue
		}
		switch {
		case strings.HasPrefix(k.Dst, "external::"):
			dropExternal = append(dropExternal, k)
		case !nvNodeIDs[k.Dst]:
			// ts dst is a concrete id (probably heuristic-rewritten) that
			// native's node set never produced — likely a wrong rewrite.
			dropMisrewrite = append(dropMisrewrite, k)
		default:
			// ts dst is a real native node, but no native edge connects them
			// — potentially a genuine miss in the native backend.
			dropGenuine = append(dropGenuine, k)
		}
	}
	for _, s := range [][]triple{dropExternal, dropMisrewrite, dropGenuine} {
		sort.Slice(s, func(i, j int) bool {
			if s[i].Src != s[j].Src {
				return s[i].Src < s[j].Src
			}
			if s[i].Kind != s[j].Kind {
				return s[i].Kind < s[j].Kind
			}
			return s[i].Dst < s[j].Dst
		})
	}

	// --- Write report ---
	reportPath := filepath.Join(repoRoot, "docs", "plans", "2026-05-20-graph-native-ast-parity-report.md")
	if err := os.MkdirAll(filepath.Dir(reportPath), 0o755); err != nil {
		t.Logf("mkdir report dir: %v", err)
		return
	}
	commit := gitShortSHA(repoRoot)

	var buf strings.Builder
	fmt.Fprintf(&buf, "# Native vs Tree-sitter Go Backend Parity Report\n\n")
	fmt.Fprintf(&buf, "_Advisory only — generated by `TestNativeBackendParityReport` (N1.14)._\n\n")
	fmt.Fprintf(&buf, "Regenerate with:\n\n")
	fmt.Fprintf(&buf, "```\n")
	fmt.Fprintf(&buf, "go test -tags=parity -count=1 ./internal/graph/cache/ \\\n")
	fmt.Fprintf(&buf, "    -run TestNativeBackendParityReport -v\n")
	fmt.Fprintf(&buf, "```\n\n")
	fmt.Fprintf(&buf, "## Run metadata\n\n")
	fmt.Fprintf(&buf, "- Timestamp: %s\n", time.Now().UTC().Format(time.RFC3339))
	fmt.Fprintf(&buf, "- devpilot commit: `%s`\n", commit)
	fmt.Fprintf(&buf, "- Repo path: `%s`\n\n", repoRoot)
	fmt.Fprintf(&buf, "## Edge counts\n\n")
	fmt.Fprintf(&buf, "| Backend | Files parsed | Nodes | Edges |\n")
	fmt.Fprintf(&buf, "|---------|--------------|-------|-------|\n")
	fmt.Fprintf(&buf, "| tree-sitter | %d | %d | %d |\n", res1.FilesParsed, len(tsNodes), len(tsEdges))
	fmt.Fprintf(&buf, "| native      | %d | %d | %d |\n\n", res2.FilesParsed, len(nvNodes), len(nvEdges))

	fmt.Fprintf(&buf, "## Coverage: (src, kind) pairs from tree-sitter present in native\n\n")
	total := len(tsSrcKind)
	pct := 100.0
	if total > 0 {
		pct = 100.0 * float64(coverageHits) / float64(total)
	}
	fmt.Fprintf(&buf, "- Total tree-sitter (src, kind) pairs: %d\n", total)
	fmt.Fprintf(&buf, "- Covered by native: %d (%.2f%%)\n", coverageHits, pct)
	fmt.Fprintf(&buf, "- Missed by native: %d\n\n", len(coverageMisses))
	if len(coverageMisses) > 0 {
		fmt.Fprintf(&buf, "Sample misses (up to 10):\n\n")
		fmt.Fprintf(&buf, "| src | kind |\n|-----|------|\n")
		for _, m := range coverageMisses[:min(10, len(coverageMisses))] {
			fmt.Fprintf(&buf, "| `%s` | `%s` |\n", m.Src, m.Kind)
		}
		fmt.Fprintf(&buf, "\n")
	}

	fmt.Fprintf(&buf, "## Net new: edges native added that tree-sitter did not\n\n")
	fmt.Fprintf(&buf, "- Count: %d\n\n", len(netNew))
	if len(netNew) > 0 {
		fmt.Fprintf(&buf, "Sample (up to 10):\n\n")
		fmt.Fprintf(&buf, "| src | dst | kind |\n|-----|-----|------|\n")
		for _, e := range netNew[:min(10, len(netNew))] {
			fmt.Fprintf(&buf, "| `%s` | `%s` | `%s` |\n", e.Src, e.Dst, e.Kind)
		}
		fmt.Fprintf(&buf, "\n")
	}

	fmt.Fprintf(&buf, "## Net removed: edges tree-sitter had that native does not\n\n")
	fmt.Fprintf(&buf, "Grouped by reason:\n\n")
	fmt.Fprintf(&buf, "| reason | count |\n|--------|-------|\n")
	fmt.Fprintf(&buf, "| A. `external::*` placeholder dropped (expected) | %d |\n", len(dropExternal))
	fmt.Fprintf(&buf, "| B. tree-sitter heuristic rewrote to a target native never produced (likely wrong rewrite) | %d |\n", len(dropMisrewrite))
	fmt.Fprintf(&buf, "| C. tree-sitter dst exists in native nodes but no native edge connects them (potential miss) | %d |\n\n", len(dropGenuine))

	writeSampleSection(&buf, "Reason A samples (external dropped)", dropExternal)
	writeSampleSection(&buf, "Reason B samples (heuristic mis-rewrite)", dropMisrewrite)
	writeSampleSection(&buf, "Reason C samples (potential native miss)", dropGenuine)

	if err := os.WriteFile(reportPath, []byte(buf.String()), 0o644); err != nil {
		t.Logf("write report: %v", err)
		return
	}
	t.Logf("parity report written: %s", reportPath)
}

type parityTriple struct{ Src, Dst, Kind string }

func writeSampleSection(buf *strings.Builder, title string, edges []parityTriple) {
	if len(edges) == 0 {
		return
	}
	fmt.Fprintf(buf, "### %s (up to 10)\n\n", title)
	fmt.Fprintf(buf, "| src | dst | kind |\n|-----|-----|------|\n")
	for _, e := range edges[:min(10, len(edges))] {
		fmt.Fprintf(buf, "| `%s` | `%s` | `%s` |\n", e.Src, e.Dst, e.Kind)
	}
	fmt.Fprintf(buf, "\n")
}

// findRepoRoot walks upward from this test file until it finds the go.mod that
// declares the devpilot module.
func findRepoRoot(t *testing.T) string {
	t.Helper()
	_, file, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("runtime.Caller failed")
	}
	dir := filepath.Dir(file)
	for i := 0; i < 8; i++ {
		gm := filepath.Join(dir, "go.mod")
		if data, err := os.ReadFile(gm); err == nil {
			if strings.Contains(string(data), "module github.com/siyuqian/devpilot") {
				abs, err := filepath.Abs(dir)
				if err != nil {
					t.Fatalf("abs: %v", err)
				}
				return abs
			}
		}
		dir = filepath.Dir(dir)
	}
	t.Fatal("could not locate devpilot module root")
	return ""
}

type dumpNode struct{ ID string }
type dumpEdge struct{ Src, Dst, Kind string }

func dumpGraph(t *testing.T, dbPath string) ([]dumpNode, []dumpEdge) {
	t.Helper()
	db, err := sql.Open("sqlite", dbPath+"?_pragma=journal_mode(WAL)")
	if err != nil {
		t.Fatalf("open %s: %v", dbPath, err)
	}
	defer func() { _ = db.Close() }()

	var nodes []dumpNode
	rows, err := db.Query(`SELECT id FROM nodes`)
	if err != nil {
		t.Fatalf("query nodes: %v", err)
	}
	for rows.Next() {
		var n dumpNode
		if err := rows.Scan(&n.ID); err != nil {
			_ = rows.Close()
			t.Fatalf("scan node: %v", err)
		}
		nodes = append(nodes, n)
	}
	_ = rows.Close()

	var edges []dumpEdge
	rows, err = db.Query(`SELECT src, dst, kind FROM edges`)
	if err != nil {
		t.Fatalf("query edges: %v", err)
	}
	for rows.Next() {
		var e dumpEdge
		if err := rows.Scan(&e.Src, &e.Dst, &e.Kind); err != nil {
			_ = rows.Close()
			t.Fatalf("scan edge: %v", err)
		}
		edges = append(edges, e)
	}
	_ = rows.Close()
	return nodes, edges
}

func gitShortSHA(repo string) string {
	cmd := exec.Command("git", "-C", repo, "rev-parse", "--short", "HEAD")
	out, err := cmd.Output()
	if err != nil {
		return "unknown"
	}
	return strings.TrimSpace(string(out))
}

